// Source tags: every piece of content says where it came from.
// موثّق = from an authoritative source, من كلام الشيخ = the sheikh's own words,
// ملخّص آلي = generated by the AI.
import { Check, Sparkle, User } from "./Icons.jsx";

export function SourceTag({ kind, children }) {
  if (kind === "verified")
    return <span className="tag tag-verified"><Check /> {children || "موثّق"}</span>;
  if (kind === "ai")
    return <span className="tag tag-ai"><Sparkle /> {children || "ملخّص آلي"}</span>;
  if (kind === "warn")
    return <span className="tag tag-warn">{children}</span>;
  return <span className="tag tag-sheikh"><User size={13} /> {children || "من كلام الشيخ"}</span>;
}

// Clickable timestamp pill that seeks the player
export function TimePill({ time, onClick }) {
  return (
    <button className="time-pill" onClick={onClick} title="انتقل إلى هذه الدقيقة">
      {time}
    </button>
  );
}
